//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knowledge.Prospector.UIEnvironment {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class UISettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UISettings defaultInstance = ((UISettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UISettings())));
        
        public static UISettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Knowledge.Net")]
        public string OutputOntologyProviderName {
            get {
                return ((string)(this["OutputOntologyProviderName"]));
            }
            set {
                this["OutputOntologyProviderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DocumentsProviderSettings {
            get {
                return ((string)(this["DocumentsProviderSettings"]));
            }
            set {
                this["DocumentsProviderSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$data\\Results\\KnowledgeNetOntology.txt")]
        public string OutputOntologySettings {
            get {
                return ((string)(this["OutputOntologySettings"]));
            }
            set {
                this["OutputOntologySettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$data\\Results\\Dump.bin")]
        public string LoadFromDumpFileName {
            get {
                return ((string)(this["LoadFromDumpFileName"]));
            }
            set {
                this["LoadFromDumpFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$data\\Results\\Dump.bin")]
        public string SaveToDumpFileName {
            get {
                return ((string)(this["SaveToDumpFileName"]));
            }
            set {
                this["SaveToDumpFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One Document")]
        public string DocumentsProviderProviderName {
            get {
                return ((string)(this["DocumentsProviderProviderName"]));
            }
            set {
                this["DocumentsProviderProviderName"] = value;
            }
        }
    }
}
