//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knowledge.Editor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandBar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandBar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Knowledge.Editor.CommandBar", typeof(CommandBar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmp_cb_no {
            get {
                object obj = ResourceManager.GetObject("bmp_cb_no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmp_down {
            get {
                object obj = ResourceManager.GetObject("bmp_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmp_down1 {
            get {
                object obj = ResourceManager.GetObject("bmp_down1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmp_findjps {
            get {
                object obj = ResourceManager.GetObject("bmp_findjps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmp_findjps2 {
            get {
                object obj = ResourceManager.GetObject("bmp_findjps2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmp_findjps21 {
            get {
                object obj = ResourceManager.GetObject("bmp_findjps21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmp_open {
            get {
                object obj = ResourceManager.GetObject("bmp_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmp_opts {
            get {
                object obj = ResourceManager.GetObject("bmp_opts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmp_remove {
            get {
                object obj = ResourceManager.GetObject("bmp_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmp_up {
            get {
                object obj = ResourceManager.GetObject("bmp_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmp_up1 {
            get {
                object obj = ResourceManager.GetObject("bmp_up1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmp_visualize {
            get {
                object obj = ResourceManager.GetObject("bmp_visualize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmp_visualize2 {
            get {
                object obj = ResourceManager.GetObject("bmp_visualize2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmp_weave {
            get {
                object obj = ResourceManager.GetObject("bmp_weave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap browse3 {
            get {
                object obj = ResourceManager.GetObject("browse3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap commit {
            get {
                object obj = ResourceManager.GetObject("commit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap commit1 {
            get {
                object obj = ResourceManager.GetObject("commit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap commit3 {
            get {
                object obj = ResourceManager.GetObject("commit3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap convert1 {
            get {
                object obj = ResourceManager.GetObject("convert1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete2 {
            get {
                object obj = ResourceManager.GetObject("delete2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string enAction {
            get {
                return ResourceManager.GetString("enAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string enBuild {
            get {
                return ResourceManager.GetString("enBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string enData {
            get {
                return ResourceManager.GetString("enData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string enDatabase {
            get {
                return ResourceManager.GetString("enDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string enDebug {
            get {
                return ResourceManager.GetString("enDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        internal static string enDiagram {
            get {
                return ResourceManager.GetString("enDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string enEdit {
            get {
                return ResourceManager.GetString("enEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string enFile {
            get {
                return ResourceManager.GetString("enFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string enFormat {
            get {
                return ResourceManager.GetString("enFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        internal static string enFrames {
            get {
                return ResourceManager.GetString("enFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string enHelp {
            get {
                return ResourceManager.GetString("enHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string enImage {
            get {
                return ResourceManager.GetString("enImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string enProject {
            get {
                return ResourceManager.GetString("enProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string enQuery {
            get {
                return ResourceManager.GetString("enQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string enSchema {
            get {
                return ResourceManager.GetString("enSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string enStyles {
            get {
                return ResourceManager.GetString("enStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string enTable {
            get {
                return ResourceManager.GetString("enTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string enTools {
            get {
                return ResourceManager.GetString("enTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string enView {
            get {
                return ResourceManager.GetString("enView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string enWindow {
            get {
                return ResourceManager.GetString("enWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string enXML {
            get {
                return ResourceManager.GetString("enXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap insert {
            get {
                object obj = ResourceManager.GetObject("insert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap insert2 {
            get {
                object obj = ResourceManager.GetObject("insert2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        internal static string jaAction {
            get {
                return ResourceManager.GetString("jaAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ビルド.
        /// </summary>
        internal static string jaBuild {
            get {
                return ResourceManager.GetString("jaBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ.
        /// </summary>
        internal static string jaData {
            get {
                return ResourceManager.GetString("jaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データベース.
        /// </summary>
        internal static string jaDatabase {
            get {
                return ResourceManager.GetString("jaDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デバッグ.
        /// </summary>
        internal static string jaDebug {
            get {
                return ResourceManager.GetString("jaDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダイアグラム.
        /// </summary>
        internal static string jaDiagram {
            get {
                return ResourceManager.GetString("jaDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        internal static string jaEdit {
            get {
                return ResourceManager.GetString("jaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル.
        /// </summary>
        internal static string jaFile {
            get {
                return ResourceManager.GetString("jaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書式.
        /// </summary>
        internal static string jaFormat {
            get {
                return ResourceManager.GetString("jaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フレーム.
        /// </summary>
        internal static string jaFrames {
            get {
                return ResourceManager.GetString("jaFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘルプ.
        /// </summary>
        internal static string jaHelp {
            get {
                return ResourceManager.GetString("jaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to イメージ.
        /// </summary>
        internal static string jaImage {
            get {
                return ResourceManager.GetString("jaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロジェクト.
        /// </summary>
        internal static string jaProject {
            get {
                return ResourceManager.GetString("jaProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クエリ.
        /// </summary>
        internal static string jaQuery {
            get {
                return ResourceManager.GetString("jaQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スキーマ.
        /// </summary>
        internal static string jaSchema {
            get {
                return ResourceManager.GetString("jaSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スタイル.
        /// </summary>
        internal static string jaStyles {
            get {
                return ResourceManager.GetString("jaStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テーブル.
        /// </summary>
        internal static string jaTable {
            get {
                return ResourceManager.GetString("jaTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツール.
        /// </summary>
        internal static string jaTools {
            get {
                return ResourceManager.GetString("jaTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示.
        /// </summary>
        internal static string jaView {
            get {
                return ResourceManager.GetString("jaView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウ.
        /// </summary>
        internal static string jaWindow {
            get {
                return ResourceManager.GetString("jaWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string jaXML {
            get {
                return ResourceManager.GetString("jaXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kn_add {
            get {
                object obj = ResourceManager.GetObject("kn_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kn_convert {
            get {
                object obj = ResourceManager.GetObject("kn_convert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kn_refresh {
            get {
                object obj = ResourceManager.GetObject("kn_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kn_rem {
            get {
                object obj = ResourceManager.GetObject("kn_rem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu_bkg {
            get {
                object obj = ResourceManager.GetObject("menu_bkg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu_bkg1 {
            get {
                object obj = ResourceManager.GetObject("menu_bkg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap otheroptions {
            get {
                object obj = ResourceManager.GetObject("otheroptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh1 {
            get {
                object obj = ResourceManager.GetObject("refresh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap servicerunning {
            get {
                object obj = ResourceManager.GetObject("servicerunning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
